prompts:
  - prompt_id: copycolors-a
    expected_answer: " A"
    target_variable: answer_pointer
  - prompt_id: copycolors-d
    expected_answer: " D"
    target_variable: answer_pointer
  - prompt_id: copycolors-token-blue
    expected_answer: " B"
    target_variable: answer_token
  - prompt_id: copycolors-token-yellow
    expected_answer: " B"
    target_variable: answer_token
